# -*- makefile -*-
#
# This file is automatically generated by configure.
# Do not hand edit.

OSTYPE		:= linux-gnueabihf
MACHINETYPE	:= armv7l
PLATFORM	:= armv7l-unknown-linux-gnueabihf
FULLOSTYPE	:= unknown-linux-gnueabihf
